
server:
  port: 8085


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CourierDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


